name: mishon_ems_mobile
description: Enterprise Floor Management and Traceability Client Application for Mishon Solutions EMS.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  intl: ^0.18.1
  http: ^1.2.1
  excel: ^4.0.0
  path_provider: ^2.1.0

  csv: ^6.0.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
